// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFrax1x97_bi4tND3xPgIoAPT5MJbIvVw',
    appId: '1:42256760557:web:b1bf8a26df2f345e7cd6e4',
    messagingSenderId: '42256760557',
    projectId: 'foodysl',
    authDomain: 'foodysl.firebaseapp.com',
    storageBucket: 'foodysl.appspot.com',
    measurementId: 'G-7K7YZBBHLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_fEGMGMWo05RxMV4-Gn14d4F9_OuaeKE',
    appId: '1:42256760557:android:c78cf2a60e132f247cd6e4',
    messagingSenderId: '42256760557',
    projectId: 'foodysl',
    storageBucket: 'foodysl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMhAi1Ax_E-5SvQrjQ4o_OkMkpx4Ft50Y',
    appId: '1:42256760557:ios:2099217c4d6e11987cd6e4',
    messagingSenderId: '42256760557',
    projectId: 'foodysl',
    storageBucket: 'foodysl.appspot.com',
    iosClientId:
        '42256760557-jr2t2ku2bcuio4eop6sunvkphptto900.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMhAi1Ax_E-5SvQrjQ4o_OkMkpx4Ft50Y',
    appId: '1:42256760557:ios:2099217c4d6e11987cd6e4',
    messagingSenderId: '42256760557',
    projectId: 'foodysl',
    storageBucket: 'foodysl.appspot.com',
    iosClientId:
        '42256760557-jr2t2ku2bcuio4eop6sunvkphptto900.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodx',
  );
}
